# Generated by Django 5.2 on 2025-04-22 14:52

import datetime
import django.db.models.deletion
import reel_logger_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(path=reel_logger_app.models.get_footage_root, recursive=True, unique=True)),
                ('hash', models.CharField(blank=True, editable=False, max_length=32)),
                ('length', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('has_audio', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('logged', models.BooleanField(default=False)),
                ('preview', models.FileField(blank=True, editable=False, null=True, upload_to='previews/')),
                ('original_filename', models.CharField(blank=True, default='', editable=False, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('script_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('comment', models.TextField()),
                ('footage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.footage')),
            ],
        ),
        migrations.CreateModel(
            name='FootageTake',
            fields=[
                ('pk', models.CompositePrimaryKey('footage_id', 'take_scene', 'take_shot', 'take_no', blank=True, editable=False, primary_key=True, serialize=False)),
                ('take_shot', models.CharField(max_length=64)),
                ('take_no', models.PositiveSmallIntegerField()),
                ('start_time', models.DurationField()),
                ('footage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.footage')),
                ('take_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('pk', models.CompositePrimaryKey('scene_id', 'shot', blank=True, editable=False, primary_key=True, serialize=False)),
                ('shot', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('pk', models.CompositePrimaryKey('shot_scene', 'shot_name', 'take_no', blank=True, editable=False, primary_key=True, serialize=False)),
                ('shot_name', models.CharField(max_length=64)),
                ('take_no', models.PositiveSmallIntegerField()),
                ('marked_scene', models.PositiveSmallIntegerField(blank=True)),
                ('marked_shot', models.CharField(blank=True, max_length=64)),
                ('marked_take', models.PositiveSmallIntegerField(blank=True)),
                ('rating', models.SmallIntegerField(blank=True, default=0)),
                ('notes', models.TextField(blank=True)),
                ('footage', models.ManyToManyField(through='reel_logger_app.FootageTake', through_fields=('take', 'footage'), to='reel_logger_app.footage')),
                ('shot', models.ForeignObject(from_fields=('shot_scene', 'shot_name'), on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.shot', to_fields=('scene_id', 'shot'))),
                ('shot_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.scene')),
            ],
        ),
        migrations.AddField(
            model_name='footagetake',
            name='take',
            field=models.ForeignObject(from_fields=('take_scene', 'take_shot', 'take_no'), on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.take', to_fields=('shot_scene', 'shot_name', 'take_no')),
        ),
    ]
