# Generated by Django 5.1.7 on 2025-04-01 08:16

import datetime
import django.db.models.deletion
import reel_logger_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(path=reel_logger_app.models.get_footage_root, recursive=True, unique=True)),
                ('hash', models.CharField(blank=True, editable=False, max_length=32)),
                ('length', models.DurationField(blank=True, default=datetime.timedelta(0))),
                ('has_audio', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('comment', models.TextField()),
                ('footage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.footage')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_no', models.PositiveSmallIntegerField()),
                ('start_time', models.DurationField()),
                ('marked_scene', models.PositiveSmallIntegerField(blank=True)),
                ('marked_shot', models.CharField(blank=True, max_length=64)),
                ('marked_take', models.PositiveSmallIntegerField(blank=True)),
                ('rating', models.SmallIntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('footage', models.ManyToManyField(to='reel_logger_app.footage')),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.shot')),
            ],
        ),
    ]
