# Generated by Django 5.1.7 on 2025-03-31 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(blank=True, null=True, recursive=True)),
                ('hash', models.CharField(max_length=32)),
                ('length', models.DurationField()),
                ('has_audio', models.BooleanField()),
                ('has_video', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField()),
                ('comment', models.TextField()),
                ('footage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.footage')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.scene')),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_no', models.PositiveSmallIntegerField()),
                ('start_time', models.DurationField()),
                ('marked_scene', models.PositiveSmallIntegerField()),
                ('marked_shot', models.CharField(max_length=64)),
                ('marked_take', models.PositiveSmallIntegerField()),
                ('rating', models.SmallIntegerField()),
                ('notes', models.TextField()),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reel_logger_app.shot')),
            ],
        ),
    ]
