# Generated by Django 5.1.7 on 2025-04-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_logger_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='hash',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='footage',
            name='length',
            field=models.DurationField(blank=True, default=0),
        ),
    ]
