# Generated by Django 5.1.7 on 2025-04-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_logger_app', '0002_alter_take_footage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='footage',
            field=models.ManyToManyField(to='reel_logger_app.footage'),
        ),
    ]
