# Generated by Django 5.1.7 on 2025-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_logger_app', '0003_alter_take_footage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='footage',
        ),
        migrations.AddField(
            model_name='footage',
            name='takes',
            field=models.ManyToManyField(to='reel_logger_app.take'),
        ),
    ]
