# Generated by Django 5.1.7 on 2025-04-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reel_logger_app', '0004_remove_take_footage_footage_takes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footage',
            name='takes',
        ),
        migrations.AddField(
            model_name='take',
            name='footage',
            field=models.ManyToManyField(related_name='takes', to='reel_logger_app.take'),
        ),
    ]
