# settings file template for the project
# settings.py reads a file called 'secret.toml'
# it should look something like this

# mandatory settings for django
[django]
debug = true
secret_key = 'django-insecure-y9zwionx8mgc6^&(x4)uds+q6dbb6r!cx8uxm67-v8d64*=s%g'
media_path = '/'
allowed_hosts = ['.localhost', '127.0.0.1', '[::1]']

# defines database settings
# optional : sqlite3 is used by default
[database]
type = 'mysql'
host = "127.0.0.1"
port = "3306"
name = "footage"
user = "myuser"
password = "mypassword"
