[database]
host = "127.0.0.1"
port = "3306"
name = "footage"
user = "myuser"
password = "mypassword"

[django]
secret_key = 'django-insecure-y9zwionx8mgc6^&(x4)uds+q6dbb6r!cx8uxm67-v8d64*=s%g'
media_path = '/'
